import { aboutDefaults } from "@/lib/about";
import type { CmsData, CmsSeo } from "@/lib/cms-schema";
import { defaultBlockStyle, defaultImageAsset, defaultTextStyle } from "@/lib/cms-style";

const defaultSeo = (overrides: Partial<CmsSeo>): CmsSeo => ({
  pageTitle: "GoGet 蝸牛外送",
  metaDescription: "GoGet 提供消費者、騎手、店家三端入口與 CMS 內容管理後台。",
  canonicalPath: "/",
  ogTitle: "GoGet 蝸牛外送",
  ogDescription: "GoGet 提供消費者、騎手、店家三端入口與 CMS 內容管理後台。",
  ogImageUrl: "/logo.png",
  robotsIndex: true,
  robotsFollow: true,
  ...overrides,
});

export const cmsDefaults: CmsData = {
  site: {
    siteName: "GoGet 蝸牛外送",
    siteUrl: "https://snail-delivery.vercel.app",
    logo: defaultImageAsset("/logo.png", "GoGet 蝸牛外送品牌標誌", {
      desktopHeight: 72,
      mobileHeight: 72,
      objectFit: "contain",
    }),
    organizationName: "GoGet 蝸牛外送",
    footerTitle: "同一套內容中樞，管理所有外送入口。",
    footerDescription:
      "CMS 後台更新後，首頁、消費者、騎手、店家頁面會同步刷新，圖片也會直接上傳到 Vercel Blob。",
    footerTitleStyle: defaultTextStyle({
      fontSize: "2xl",
      fontWeight: "900",
      textColor: "brand.white",
    }),
    footerDescriptionStyle: defaultTextStyle({
      fontSize: "base",
      fontWeight: "400",
      textColor: "#d9e4ff",
      lineHeight: "relaxed",
    }),
    footerLinkGroups: [
      {
        title: "角色入口",
        links: [
          { label: "消費者", href: "/consumer" },
          { label: "騎手", href: "/courier" },
          { label: "店家", href: "/merchant" },
        ],
      },
      {
        title: "後台與下載",
        links: [
          { label: "內容後台", href: "/admin" },
          { label: "下載入口", href: "/#download-cards" },
        ],
      },
    ],
    footerStyle: defaultBlockStyle({
      backgroundColor: "brand.ink",
      foregroundColor: "brand.white",
      borderRadius: "2xl",
      paddingX: "10",
      paddingY: "10",
      shadow: "lg",
    }),
    defaultSeoImageUrl: "/logo.png",
  },
  home: {
    header: {
      subtitle: "CMS V2 可視化內容管理後台",
      subtitleStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "500",
        textColor: "#5d6b87",
      }),
      navItems: [
        { label: "消費者", href: "/consumer" },
        { label: "騎手", href: "/courier" },
        { label: "店家", href: "/merchant" },
        { label: "後台", href: "/admin" },
      ],
      aboutLink: { label: "關於我們", href: "/about" },
      cta: { label: "立即下載 App", href: "/#download-cards" },
      blockStyle: defaultBlockStyle({
        backgroundColor: "#ffffffcc",
        borderColor: "#d9e4ff",
        borderRadius: "full",
        paddingX: "6",
        paddingY: "4",
        shadow: "md",
      }),
    },
    hero: {
      badge: "Snail Delivery CMS V2",
      title: "一個後台，同步管理 GoGet 全站內容與下載入口。",
      subtitle:
        "首頁、消費者、騎手、店家頁面共用同一份 CMS 資料，讓營運調整文案、圖片、下載連結與 SEO 設定時，不必改程式碼。",
      primaryLabel: "查看下載入口",
      primaryHref: "#download-cards",
      secondaryLabel: "了解 Launch Flow",
      secondaryHref: "#launch-flow",
      deviceBadge: "目前裝置：自動判斷下載平台",
      secondaryBadge: "Blob CMS 即時同步",
      heroImage: defaultImageAsset("/images/user.png", "GoGet 首頁展示圖", {
        desktopHeight: 360,
        mobileHeight: 260,
      }),
      badgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.blueDeep",
      }),
      titleStyle: defaultTextStyle({
        fontSize: "6xl",
        fontWeight: "900",
        textColor: "brand.ink",
        lineHeight: "tight",
      }),
      subtitleStyle: defaultTextStyle({
        fontSize: "lg",
        fontWeight: "400",
        textColor: "#44536d",
        lineHeight: "relaxed",
      }),
      deviceBadgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.white",
      }),
      secondaryBadgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.ink",
      }),
      sectionStyle: defaultBlockStyle({
        backgroundColor: "#ffffffd9",
        borderColor: "#ffffff",
        borderRadius: "2xl",
        paddingX: "10",
        paddingY: "10",
        shadow: "lg",
      }),
    },
    features: {
      cards: [
        {
          eyebrow: "資料一致",
          title: "首頁與角色頁共用同一份 CMS",
          description: "修正文案後，前台與後台不再各自維護，避免欄位脫節。",
          eyebrowStyle: defaultTextStyle({
            fontSize: "xs",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "700",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "base",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#ffffffd9",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
        {
          eyebrow: "圖片控管",
          title: "Blob 圖片上傳、覆寫與裁切設定一起管理",
          description: "圖片能設定 alt、裁切焦點、高度與 object fit，縮短上稿時間。",
          eyebrowStyle: defaultTextStyle({
            fontSize: "xs",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "700",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "base",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#ffffffd9",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
        {
          eyebrow: "GEO / SEO",
          title: "Metadata、JSON-LD、robots、sitemap 一次補齊",
          description: "首頁與三個角色頁各自擁有獨立 metadata，搜尋引擎收錄基線完整。",
          eyebrowStyle: defaultTextStyle({
            fontSize: "xs",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "700",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "base",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#ffffffd9",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
      ],
      sectionStyle: defaultBlockStyle({
        backgroundColor: "transparent",
        foregroundColor: "brand.ink",
        borderColor: "transparent",
        borderRadius: "none",
        paddingX: "0",
        paddingY: "0",
        shadow: "none",
      }),
    },
    downloadCards: [
      {
        key: "consumer",
        eyebrow: "Consumer App",
        title: "GoGet 消費者",
        description: "提供使用者快速瀏覽餐廳、下單與追蹤配送進度的行動入口。",
        audience: "一般消費者與家庭用戶",
        image: defaultImageAsset("/images/user.png", "GoGet 消費者 App 畫面", {
          desktopHeight: 256,
          mobileHeight: 224,
        }),
        iosUrl:
          "https://apps.apple.com/tw/app/%E8%9D%B8%E7%89%9B%E5%A4%96%E9%80%81/id6751226746",
        androidUrl:
          "https://play.google.com/store/apps/details?id=plus.H5F0A257F",
        highlights: ["即時追蹤", "優惠活動", "多店家探索"],
        eyebrowStyle: defaultTextStyle({
          fontSize: "xs",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        titleStyle: defaultTextStyle({
          fontSize: "2xl",
          fontWeight: "900",
          textColor: "brand.ink",
          lineHeight: "tight",
        }),
        audienceStyle: defaultTextStyle({
          fontSize: "sm",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        descriptionStyle: defaultTextStyle({
          fontSize: "base",
          fontWeight: "400",
          textColor: "#44536d",
          lineHeight: "relaxed",
        }),
        blockStyle: defaultBlockStyle({
          backgroundColor: "#fffffff0",
          borderColor: "#dce9ff",
          borderRadius: "xl",
          paddingX: "6",
          paddingY: "6",
          shadow: "md",
        }),
      },
      {
        key: "courier",
        eyebrow: "Courier App",
        title: "GoGet Turbo",
        description: "讓外送騎手用更清楚的任務節奏與收入資訊，穩定接單與出勤。",
        audience: "兼職與全職騎手",
        image: defaultImageAsset("/images/rider.png", "GoGet Turbo App 畫面", {
          desktopHeight: 256,
          mobileHeight: 224,
        }),
        iosUrl:
          "https://apps.apple.com/tw/app/%E8%9D%B8%E7%89%9Bturbo/id6751255326",
        androidUrl:
          "https://play.google.com/store/apps/details?id=plus.H5ADE2198",
        highlights: ["彈性排班", "透明收入", "即時任務"],
        eyebrowStyle: defaultTextStyle({
          fontSize: "xs",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        titleStyle: defaultTextStyle({
          fontSize: "2xl",
          fontWeight: "900",
          textColor: "brand.ink",
          lineHeight: "tight",
        }),
        audienceStyle: defaultTextStyle({
          fontSize: "sm",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        descriptionStyle: defaultTextStyle({
          fontSize: "base",
          fontWeight: "400",
          textColor: "#44536d",
          lineHeight: "relaxed",
        }),
        blockStyle: defaultBlockStyle({
          backgroundColor: "#fffffff0",
          borderColor: "#dce9ff",
          borderRadius: "xl",
          paddingX: "6",
          paddingY: "6",
          shadow: "md",
        }),
      },
      {
        key: "merchant",
        eyebrow: "Merchant App",
        title: "GoGet 店家",
        description: "協助店家管理訂單、曝光與營運資訊，快速同步菜單與品牌內容。",
        audience: "餐飲與零售合作店家",
        image: defaultImageAsset("/images/merchant.png", "GoGet 店家 App 畫面", {
          desktopHeight: 256,
          mobileHeight: 224,
        }),
        iosUrl: "https://apps.apple.com/app/id6751261624",
        androidUrl:
          "https://play.google.com/store/apps/details?id=plus.H58A1C9BB",
        highlights: ["零固定費", "營運工具", "品牌曝光"],
        eyebrowStyle: defaultTextStyle({
          fontSize: "xs",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        titleStyle: defaultTextStyle({
          fontSize: "2xl",
          fontWeight: "900",
          textColor: "brand.ink",
          lineHeight: "tight",
        }),
        audienceStyle: defaultTextStyle({
          fontSize: "sm",
          fontWeight: "700",
          textColor: "brand.blueDeep",
        }),
        descriptionStyle: defaultTextStyle({
          fontSize: "base",
          fontWeight: "400",
          textColor: "#44536d",
          lineHeight: "relaxed",
        }),
        blockStyle: defaultBlockStyle({
          backgroundColor: "#fffffff0",
          borderColor: "#dce9ff",
          borderRadius: "xl",
          paddingX: "6",
          paddingY: "6",
          shadow: "md",
        }),
      },
    ],
    launchFlow: {
      eyebrow: "Launch Flow",
      title: "從 CMS 編輯到前台發布，路徑保持單純。",
      description:
        "內容管理後台更新文字與圖片後，系統會將資料寫入 Blob，並重新整理首頁與各角色頁的快取。",
      eyebrowStyle: defaultTextStyle({
        fontSize: "xs",
        fontWeight: "700",
        textColor: "brand.yellow",
      }),
      titleStyle: defaultTextStyle({
        fontSize: "4xl",
        fontWeight: "900",
        textColor: "brand.white",
        lineHeight: "tight",
      }),
      descriptionStyle: defaultTextStyle({
        fontSize: "base",
        fontWeight: "400",
        textColor: "#d9e4ff",
        lineHeight: "relaxed",
      }),
      leftBlockStyle: defaultBlockStyle({
        backgroundColor: "brand.ink",
        foregroundColor: "brand.white",
        borderColor: "#243a67",
        borderRadius: "xl",
        paddingX: "8",
        paddingY: "8",
        shadow: "lg",
      }),
      rightBlockStyle: defaultBlockStyle({
        backgroundColor: "transparent",
        foregroundColor: "brand.ink",
        borderColor: "transparent",
        borderRadius: "none",
        paddingX: "0",
        paddingY: "0",
        shadow: "none",
      }),
      steps: [
        {
          index: "01",
          title: "選擇角色",
          description: "先確認你要下載消費者、騎手或店家端 App。",
          indexStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "900",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#fffffff0",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
        {
          index: "02",
          title: "前往商店",
          description: "依照裝置類型跳轉至 App Store 或 Google Play。",
          indexStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "900",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#fffffff0",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
        {
          index: "03",
          title: "完成啟用",
          description: "安裝完成後即可登入並開始使用 GoGet 服務。",
          indexStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "700",
            textColor: "brand.blueDeep",
          }),
          titleStyle: defaultTextStyle({
            fontSize: "xl",
            fontWeight: "900",
            textColor: "brand.ink",
            lineHeight: "tight",
          }),
          descriptionStyle: defaultTextStyle({
            fontSize: "sm",
            fontWeight: "400",
            textColor: "#55627c",
            lineHeight: "relaxed",
          }),
          blockStyle: defaultBlockStyle({
            backgroundColor: "#fffffff0",
            borderColor: "#dce9ff",
            borderRadius: "xl",
            paddingX: "6",
            paddingY: "6",
            shadow: "md",
          }),
        },
      ],
    },
    seo: defaultSeo({
      pageTitle: "GoGet 蝸牛外送 | CMS V2 可視化後台",
      metaDescription:
        "GoGet 蝸牛外送 CMS V2，提供繁體中文後台、首頁下載入口、角色頁與 SEO / GEO 內容管理。",
      canonicalPath: "/",
      ogTitle: "GoGet 蝸牛外送 | CMS V2 可視化後台",
      ogDescription:
        "GoGet 蝸牛外送 CMS V2，提供繁體中文後台、首頁下載入口、角色頁與 SEO / GEO 內容管理。",
    }),
  },
  about: {
    ...aboutDefaults,
  },
  consumer: {
    hero: {
      badge: "Consumer Experience",
      title: "讓使用者從瀏覽到下單，都維持順暢且可信任的體驗。",
      description:
        "GoGet 消費者端聚焦在探索、下單與配送追蹤，讓每一次打開 App 都是明確且可預期的流程。",
      primaryLabel: "前往首頁",
      primaryHref: "/",
      secondaryLabel: "查看店家方案",
      secondaryHref: "/merchant",
      asideTitle: "Consumer Snapshot",
      stats: [
        { label: "熱門時段", value: "午餐 11:00-14:00" },
        { label: "主打能力", value: "即時追蹤" },
        { label: "內容更新", value: "CMS 即時同步" },
      ],
      heroImage: defaultImageAsset("/images/user.png", "GoGet 消費者頁英雄圖", {
        desktopHeight: 340,
        mobileHeight: 240,
      }),
      badgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.ink",
      }),
      titleStyle: defaultTextStyle({
        fontSize: "6xl",
        fontWeight: "900",
        textColor: "brand.ink",
        lineHeight: "tight",
      }),
      descriptionStyle: defaultTextStyle({
        fontSize: "lg",
        fontWeight: "400",
        textColor: "#44536d",
        lineHeight: "relaxed",
      }),
      asideTitleStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.blueDeep",
      }),
      sectionStyle: defaultBlockStyle({
        backgroundColor: "#ffffffe6",
        borderColor: "#dce9ff",
        borderRadius: "xl",
        paddingX: "8",
        paddingY: "8",
        shadow: "lg",
      }),
    },
    sections: [],
    seo: defaultSeo({
      pageTitle: "GoGet 消費者 | 訂餐與配送體驗",
      metaDescription: "了解 GoGet 消費者端如何提供清楚的訂餐、追蹤與配送體驗。",
      canonicalPath: "/consumer",
      ogTitle: "GoGet 消費者 | 訂餐與配送體驗",
      ogDescription: "了解 GoGet 消費者端如何提供清楚的訂餐、追蹤與配送體驗。",
    }),
  },
  courier: {
    hero: {
      badge: "Courier Experience",
      title: "讓騎手在高節奏工作中，也能維持清楚決策與穩定收入預期。",
      description:
        "GoGet 騎手端將收入、任務與工作節奏整理成一致介面，降低接單猶豫與資訊噪音。",
      primaryLabel: "返回首頁",
      primaryHref: "/",
      secondaryLabel: "查看消費者頁",
      secondaryHref: "/consumer",
      asideTitle: "Shift Overview",
      stats: [
        { label: "接單節奏", value: "高峰自動放大" },
        { label: "收入資訊", value: "透明可追蹤" },
        { label: "排班方式", value: "彈性上線" },
      ],
      heroImage: defaultImageAsset("/images/rider.png", "GoGet 騎手頁英雄圖", {
        desktopHeight: 340,
        mobileHeight: 240,
      }),
      badgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.ink",
      }),
      titleStyle: defaultTextStyle({
        fontSize: "6xl",
        fontWeight: "900",
        textColor: "brand.ink",
        lineHeight: "tight",
      }),
      descriptionStyle: defaultTextStyle({
        fontSize: "lg",
        fontWeight: "400",
        textColor: "#44536d",
        lineHeight: "relaxed",
      }),
      asideTitleStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.blueDeep",
      }),
      sectionStyle: defaultBlockStyle({
        backgroundColor: "#ffffffe6",
        borderColor: "#dce9ff",
        borderRadius: "xl",
        paddingX: "8",
        paddingY: "8",
        shadow: "lg",
      }),
    },
    sections: [],
    seo: defaultSeo({
      pageTitle: "GoGet 騎手 | 任務與收入節奏",
      metaDescription: "了解 GoGet 騎手端如何整理任務節奏、收入資訊與支援內容。",
      canonicalPath: "/courier",
      ogTitle: "GoGet 騎手 | 任務與收入節奏",
      ogDescription: "了解 GoGet 騎手端如何整理任務節奏、收入資訊與支援內容。",
    }),
  },
  merchant: {
    hero: {
      badge: "Merchant Experience",
      title: "把店家的上架、營運與品牌更新，都收斂到同一個清楚入口。",
      description:
        "GoGet 店家端聚焦在零固定費、營運效率與曝光管理，幫助店家更快理解合作價值。",
      primaryLabel: "返回首頁",
      primaryHref: "/",
      secondaryLabel: "查看消費者頁",
      secondaryHref: "/consumer",
      asideTitle: "Merchant Snapshot",
      stats: [
        { label: "固定費", value: "0 元" },
        { label: "工具面向", value: "品牌 / 營運 / 曝光" },
        { label: "更新機制", value: "CMS 同步" },
      ],
      heroImage: defaultImageAsset("/images/merchant.png", "GoGet 店家頁英雄圖", {
        desktopHeight: 340,
        mobileHeight: 240,
      }),
      badgeStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.ink",
      }),
      titleStyle: defaultTextStyle({
        fontSize: "6xl",
        fontWeight: "900",
        textColor: "brand.ink",
        lineHeight: "tight",
      }),
      descriptionStyle: defaultTextStyle({
        fontSize: "lg",
        fontWeight: "400",
        textColor: "#44536d",
        lineHeight: "relaxed",
      }),
      asideTitleStyle: defaultTextStyle({
        fontSize: "sm",
        fontWeight: "700",
        textColor: "brand.blueDeep",
      }),
      sectionStyle: defaultBlockStyle({
        backgroundColor: "#ffffffe6",
        borderColor: "#dce9ff",
        borderRadius: "xl",
        paddingX: "8",
        paddingY: "8",
        shadow: "lg",
      }),
    },
    sections: [],
    seo: defaultSeo({
      pageTitle: "GoGet 店家 | 合作與營運工具",
      metaDescription: "了解 GoGet 店家端如何呈現零固定費、營運效率與品牌曝光能力。",
      canonicalPath: "/merchant",
      ogTitle: "GoGet 店家 | 合作與營運工具",
      ogDescription: "了解 GoGet 店家端如何呈現零固定費、營運效率與品牌曝光能力。",
    }),
  },
};

cmsDefaults.consumer.sections = [
  {
    id: "consumer-trust",
    badge: "Trusted Moments",
    title: "把每一個下單瞬間，整理成更容易理解的體驗。",
    description: "從餐廳探索、品項判讀到配送更新，資訊都必須清楚。",
    badgeStyle: defaultTextStyle({
      fontSize: "sm",
      fontWeight: "700",
      textColor: "brand.blueDeep",
    }),
    titleStyle: defaultTextStyle({
      fontSize: "4xl",
      fontWeight: "900",
      textColor: "brand.ink",
      lineHeight: "tight",
    }),
    descriptionStyle: defaultTextStyle({
      fontSize: "base",
      fontWeight: "400",
      textColor: "#44536d",
      lineHeight: "relaxed",
    }),
    blockStyle: defaultBlockStyle({
      backgroundColor: "transparent",
      borderColor: "transparent",
      borderRadius: "none",
      paddingX: "0",
      paddingY: "0",
      shadow: "none",
    }),
    items: [
      {
        eyebrow: "Quality",
        title: "重點資訊先到位",
        description: "以最少阻力呈現品項、價格與配送資訊。",
        icon: "品",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Updates",
        title: "狀態變更即時可見",
        description: "訂單進度與配送狀態要能在關鍵時刻被快速理解。",
        icon: "更",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Safety",
        title: "建立安心感",
        description: "把平台規則、配送流程與聯繫方式講清楚。",
        icon: "安",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
    ],
  },
];

cmsDefaults.courier.sections = [
  {
    id: "courier-pillars",
    badge: "Three Pillars",
    title: "收入、彈性、安全，是騎手端最核心的三個承諾。",
    description: "這些內容必須能被營運快速更新，才能反映實際招募策略。",
    badgeStyle: defaultTextStyle({ fontSize: "sm", fontWeight: "700", textColor: "brand.blueDeep" }),
    titleStyle: defaultTextStyle({ fontSize: "4xl", fontWeight: "900", textColor: "brand.ink", lineHeight: "tight" }),
    descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#44536d", lineHeight: "relaxed" }),
    blockStyle: defaultBlockStyle({ backgroundColor: "transparent", borderColor: "transparent", borderRadius: "none", paddingX: "0", paddingY: "0", shadow: "none" }),
    items: [
      {
        eyebrow: "Income",
        title: "收入訊息透明",
        description: "把獎勵、單量與任務價值說清楚。",
        icon: "收",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Flexibility",
        title: "排班更自由",
        description: "讓兼職與全職騎手都能理解工作節奏。",
        icon: "彈",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Safety",
        title: "安全規範清楚",
        description: "出勤規則、支援機制與提醒資訊都應一致。",
        icon: "安",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
    ],
  },
];

cmsDefaults.merchant.sections = [
  {
    id: "merchant-zero-fee",
    badge: "Zero Fixed Fees",
    title: "先講清楚成本結構，店家才會願意繼續往下看。",
    description: "零固定費與合作門檻是最重要的轉換訊息之一。",
    badgeStyle: defaultTextStyle({ fontSize: "sm", fontWeight: "700", textColor: "brand.blueDeep" }),
    titleStyle: defaultTextStyle({ fontSize: "4xl", fontWeight: "900", textColor: "brand.ink", lineHeight: "tight" }),
    descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#44536d", lineHeight: "relaxed" }),
    blockStyle: defaultBlockStyle({ backgroundColor: "transparent", borderColor: "transparent", borderRadius: "none", paddingX: "0", paddingY: "0", shadow: "none" }),
    items: [
      {
        eyebrow: "Fee",
        title: "零固定費",
        description: "降低合作初期的決策壓力。",
        icon: "零",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Launch",
        title: "快速開通",
        description: "縮短從接洽到上線的等待時間。",
        icon: "快",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
      {
        eyebrow: "Clarity",
        title: "合作條件清楚",
        description: "把費用、流程與支援機制講完整。",
        icon: "明",
        eyebrowStyle: defaultTextStyle({ fontSize: "xs", fontWeight: "700", textColor: "brand.blueDeep" }),
        titleStyle: defaultTextStyle({ fontSize: "xl", fontWeight: "700", textColor: "brand.ink", lineHeight: "tight" }),
        descriptionStyle: defaultTextStyle({ fontSize: "base", fontWeight: "400", textColor: "#55627c", lineHeight: "relaxed" }),
        blockStyle: defaultBlockStyle({ backgroundColor: "#fffffff0", borderColor: "#dce9ff", borderRadius: "xl", paddingX: "6", paddingY: "6", shadow: "md" }),
      },
    ],
  },
];
